services:
  api:
    image: ghcr.io/k-bilaluddin/jobvault-api:latest
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: jobvault-api
    ports:
      - "5000:8080"
    env_file:
      - .env
    restart: unless-stopped

  worker:
    image: ghcr.io/k-bilaluddin/jobvault-worker:latest
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    container_name: jobvault-worker
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - default
      - jobvault-internal

networks:
  jobvault-internal:
    external: true
